import React, { useState } from 'react';
import axios from 'axios';
import jsPDF from 'jspdf';

const QueryPage = () => {
  const [faultDescription, setFaultDescription] = useState('');
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [showSimilar, setShowSimilar] = useState(true);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setResult(null);
    setError('');

    const token = localStorage.getItem('token');
    if (!token) {
      setError('Please login first');
      setLoading(false);
      return;
    }

    try {
      const response = await axios.post('https://api.vectorscan.io/query', {
        fault_description: faultDescription,
      }, {
        headers: { 'Authorization': `Bearer ${token}` },
      });

      if (response.data.error) {
        setError(response.data.error);
      } else {
        setResult(response.data.result); // Use the structured response directly!
      }
    } catch (err) {
      setError(err.response?.data?.error || 'Failed to submit query');
    } finally {
      setLoading(false);
    }
  };

// Insert your base64 image data here (example placeholder)
// const logoData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA..."; // replace with your actual logo data

const handleDownloadPDF = () => {
  if (!result) return;
  const doc = new jsPDF();
  const maxWidth = 170;
  let yPos = 20;

  // --- Branding: Add logo ---
  // Parameters: imageData, format, x, y, width, height
  doc.addImage(logoData, 'PNG', 150, 10, 40, 16); // adjust position/size as needed
  yPos += 20;

  // --- Title ---
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(22, 58, 110); // Navy blue
  doc.text(result.fault_title || 'Diagnosis Report', 15, yPos);
  yPos += 12;

  // --- Section: Diagnosis ---
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Diagnosis:', 15, yPos);
  yPos += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const diagnosisLines = doc.splitTextToSize(result.diagnosis || '', maxWidth);
  doc.text(diagnosisLines, 15, yPos);
  yPos += diagnosisLines.length * 7 + 5;

  // --- Section: Step-by-Step Troubleshooting ---
  if (result.troubleshooting_steps && result.troubleshooting_steps.length) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Step-by-Step Troubleshooting:', 15, yPos);
    yPos += 8;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    result.troubleshooting_steps.forEach(step => {
      const stepLines = doc.splitTextToSize(step, maxWidth - 7);
      doc.text("•", 18, yPos);
      doc.text(stepLines[0], 22, yPos);
      yPos += 7;
      for (let i = 1; i < stepLines.length; i++) {
        doc.text(stepLines[i], 22, yPos);
        yPos += 7;
      }
      if (yPos > 265) { doc.addPage(); yPos = 20; }
    });
    yPos += 5;
  }

  // --- Section: Recommended Actions ---
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Recommended Actions:', 15, yPos);
  yPos += 8;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  (result.recommended_actions || []).forEach(action => {
    const actionLines = doc.splitTextToSize(action, maxWidth - 7);
    doc.text("•", 18, yPos);
    doc.text(actionLines[0], 22, yPos);
    yPos += 7;
    for (let i = 1; i < actionLines.length; i++) {
      doc.text(actionLines[i], 22, yPos);
      yPos += 7;
    }
    if (yPos > 265) { doc.addPage(); yPos = 20; }
  });

  // --- Footer Branding ---
  doc.setDrawColor(180, 180, 180);
  doc.setLineWidth(0.5);
  doc.line(15, 285, 195, 285);

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by VectorScan Troubleshooting Platform | © 2025 VectorScan', 15, 291);

  doc.save(`VectorScan_Report_${new Date().toISOString().slice(0,10)}.pdf`);
};

  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-900 to-blue-300 flex items-center justify-center font-sans p-4">
      <div className="bg-white p-8 rounded-lg shadow-2xl w-full max-w-3xl">
        <header className="text-center mb-8">
          <img src="/vectorscan-logo.png" alt="VectorScan Logo" className="h-20 mx-auto mb-4" />
          <h1 className="text-4xl font-bold text-blue-800">VectorScan Troubleshooting Platform</h1>
          <span className="text-sm text-gray-500">Integrated with CBM Systems</span>
        </header>
        <form onSubmit={handleSubmit} className="space-y-4 bg-gray-50 p-6 rounded-lg shadow-inner mb-8">
          <div>
            <label htmlFor="fault-description" className="block text-sm font-medium text-gray-700 mb-1">Enter Fault Description</label>
            <input
              id="fault-description"
              type="text"
              value={faultDescription}
              onChange={(e) => setFaultDescription(e.target.value)}
              className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 text-base"
              placeholder="e.g., main engine overheat"
              required
            />
          </div>
          <button
            type="submit"
            disabled={loading}
            className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 disabled:bg-blue-300 flex items-center justify-center text-base font-semibold"
          >
            {loading ? 'Diagnosing...' : 'Diagnose Fault'}
          </button>
          {error && <p className="text-red-600 text-sm mt-2">{error}</p>}
        </form>
        {result && (
          <div className="p-6 bg-gray-50 rounded-lg shadow-inner">
            <h2 className="text-2xl font-semibold text-blue-800 mb-2">{result.fault_title || 'Diagnosis Result'}</h2>
            <div className="mb-4">
              <h3 className="font-bold text-gray-700 text-lg">Diagnosis</h3>
              <p className="mt-1 text-gray-800 bg-white p-3 rounded">{result.diagnosis}</p>
            </div>
            <div className="mb-4">
              <h3 className="font-bold text-gray-700 text-lg">Recommended Actions</h3>
              <ul className="list-disc pl-6 mt-1 text-gray-800 bg-white p-3 rounded">
                {(result.recommended_actions || []).map((action, idx) => (
                  <li key={idx}>{action}</li>
                ))}
              </ul>
            </div>
            <div className="flex gap-4 mt-4">
              <button
                onClick={handleDownloadPDF}
                className="bg-green-600 text-white py-2 px-4 rounded-md hover:bg-green-700 font-semibold"
              >
                Download PDF
              </button>
              {/* Add your CBM system link logic here if available */}
              <button
                className="bg-gray-300 text-blue-800 py-2 px-4 rounded-md font-semibold hover:bg-gray-400"
                disabled
              >
                View in CBM System
              </button>
            </div>
            <div className="mt-8">
              <button
                className="text-blue-600 underline mb-2"
                onClick={() => setShowSimilar(!showSimilar)}
              >
                {showSimilar ? "Hide Similar Past Faults" : "Show Similar Past Faults"}
              </button>
              {showSimilar && result.similar_faults && result.similar_faults.length > 0 && (
                <div className="overflow-x-auto bg-white p-4 rounded shadow">
                  <table className="min-w-full text-sm border-collapse">
                    <thead>
                      <tr className="bg-blue-100">
                        <th className="px-2 py-1 border">Equipment</th>
                        <th className="px-2 py-1 border">Fault</th>
                        <th className="px-2 py-1 border">Resolution</th>
                        <th className="px-2 py-1 border">Date</th>
                        <th className="px-2 py-1 border">ID</th>
                      </tr>
                    </thead>
                    <tbody>
                      {result.similar_faults.map((f, idx) => (
                        <tr key={f.id || idx}>
                          <td className="px-2 py-1 border">{f.equipment}</td>
                          <td className="px-2 py-1 border">{f.fault}</td>
                          <td className="px-2 py-1 border">{f.resolution}</td>
                          <td className="px-2 py-1 border">{f.date}</td>
                          <td className="px-2 py-1 border">{f.id}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default QueryPage;